// Code generated by protoc-gen-go.
// source: webhook.proto
// DO NOT EDIT!

/*
Package webhook is a generated protocol buffer package.

It is generated from these files:
	webhook.proto

It has these top-level messages:
	WebhookRequest
	Bucket
	Input
	Output
	HeaderValue
	Header
	Request
	WebhookFilter
*/
package webhook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request message for creating a new customer
type WebhookRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// bucket info
	Bucket *Bucket `protobuf:"bytes,2,opt,name=bucket" json:"bucket,omitempty"`
	// incomming request
	Request *Request `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
	Input   *Input   `protobuf:"bytes,4,opt,name=input" json:"input,omitempty"`
	Output  *Output  `protobuf:"bytes,5,opt,name=output" json:"output,omitempty"`
}

func (m *WebhookRequest) Reset()                    { *m = WebhookRequest{} }
func (m *WebhookRequest) String() string            { return proto.CompactTextString(m) }
func (*WebhookRequest) ProtoMessage()               {}
func (*WebhookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WebhookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WebhookRequest) GetBucket() *Bucket {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *WebhookRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *WebhookRequest) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *WebhookRequest) GetOutput() *Output {
	if m != nil {
		return m.Output
	}
	return nil
}

// Bucket - bucket info
type Bucket struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Bucket) Reset()                    { *m = Bucket{} }
func (m *Bucket) String() string            { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()               {}
func (*Bucket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bucket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bucket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Input struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Input) Reset()                    { *m = Input{} }
func (m *Input) String() string            { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()               {}
func (*Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Input) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Input) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Output struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Output) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Output) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HeaderValue struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *HeaderValue) Reset()                    { *m = HeaderValue{} }
func (m *HeaderValue) String() string            { return proto.CompactTextString(m) }
func (*HeaderValue) ProtoMessage()               {}
func (*HeaderValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HeaderValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Header struct {
	Headers map[string]*HeaderValue `protobuf:"bytes,3,rep,name=headers" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Header) GetHeaders() map[string]*HeaderValue {
	if m != nil {
		return m.Headers
	}
	return nil
}

// Request - incomming request to webhook relay service
type Request struct {
	// desired destination
	Destination string `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	// request body
	Body   []byte  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Header *Header `protobuf:"bytes,3,opt,name=header" json:"header,omitempty"`
	Method string  `protobuf:"bytes,4,opt,name=Method" json:"Method,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Request) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type WebhookFilter struct {
	Bucket      string `protobuf:"bytes,1,opt,name=bucket" json:"bucket,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination" json:"destination,omitempty"`
}

func (m *WebhookFilter) Reset()                    { *m = WebhookFilter{} }
func (m *WebhookFilter) String() string            { return proto.CompactTextString(m) }
func (*WebhookFilter) ProtoMessage()               {}
func (*WebhookFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *WebhookFilter) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *WebhookFilter) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func init() {
	proto.RegisterType((*WebhookRequest)(nil), "webhook.WebhookRequest")
	proto.RegisterType((*Bucket)(nil), "webhook.Bucket")
	proto.RegisterType((*Input)(nil), "webhook.Input")
	proto.RegisterType((*Output)(nil), "webhook.Output")
	proto.RegisterType((*HeaderValue)(nil), "webhook.HeaderValue")
	proto.RegisterType((*Header)(nil), "webhook.Header")
	proto.RegisterType((*Request)(nil), "webhook.Request")
	proto.RegisterType((*WebhookFilter)(nil), "webhook.WebhookFilter")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Webhook service

type WebhookClient interface {
	// Get all Webhook requests with filter - A server-to-client streaming RPC.
	GetWebhooks(ctx context.Context, in *WebhookFilter, opts ...grpc.CallOption) (Webhook_GetWebhooksClient, error)
}

type webhookClient struct {
	cc *grpc.ClientConn
}

func NewWebhookClient(cc *grpc.ClientConn) WebhookClient {
	return &webhookClient{cc}
}

func (c *webhookClient) GetWebhooks(ctx context.Context, in *WebhookFilter, opts ...grpc.CallOption) (Webhook_GetWebhooksClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Webhook_serviceDesc.Streams[0], c.cc, "/webhook.Webhook/GetWebhooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &webhookGetWebhooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Webhook_GetWebhooksClient interface {
	Recv() (*WebhookRequest, error)
	grpc.ClientStream
}

type webhookGetWebhooksClient struct {
	grpc.ClientStream
}

func (x *webhookGetWebhooksClient) Recv() (*WebhookRequest, error) {
	m := new(WebhookRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Webhook service

type WebhookServer interface {
	// Get all Webhook requests with filter - A server-to-client streaming RPC.
	GetWebhooks(*WebhookFilter, Webhook_GetWebhooksServer) error
}

func RegisterWebhookServer(s *grpc.Server, srv WebhookServer) {
	s.RegisterService(&_Webhook_serviceDesc, srv)
}

func _Webhook_GetWebhooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WebhookFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebhookServer).GetWebhooks(m, &webhookGetWebhooksServer{stream})
}

type Webhook_GetWebhooksServer interface {
	Send(*WebhookRequest) error
	grpc.ServerStream
}

type webhookGetWebhooksServer struct {
	grpc.ServerStream
}

func (x *webhookGetWebhooksServer) Send(m *WebhookRequest) error {
	return x.ServerStream.SendMsg(m)
}

var _Webhook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webhook.Webhook",
	HandlerType: (*WebhookServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWebhooks",
			Handler:       _Webhook_GetWebhooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "webhook.proto",
}

func init() { proto.RegisterFile("webhook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xcd, 0xaa, 0x9b, 0x40,
	0x14, 0xc7, 0x3b, 0x1a, 0x15, 0x8f, 0xf9, 0x62, 0x28, 0xa9, 0x84, 0x2e, 0x44, 0x5a, 0x2a, 0x69,
	0x08, 0x25, 0x85, 0x52, 0xba, 0x0c, 0xf4, 0x23, 0x8b, 0xd0, 0x32, 0x8b, 0x76, 0xad, 0x75, 0x20,
	0x92, 0xd4, 0x49, 0x75, 0x6c, 0xc9, 0xee, 0x3e, 0xc3, 0x7d, 0xa6, 0xfb, 0x60, 0x97, 0x99, 0x39,
	0x4a, 0xae, 0xd9, 0x64, 0xe5, 0xf9, 0xf8, 0x71, 0xfe, 0xff, 0x99, 0x39, 0xc2, 0xe8, 0x3f, 0xcf,
	0xf6, 0x42, 0x1c, 0x56, 0xa7, 0x4a, 0x48, 0x41, 0x3d, 0x4c, 0xe3, 0x07, 0x02, 0xe3, 0x5f, 0x26,
	0x66, 0xfc, 0x6f, 0xc3, 0x6b, 0x49, 0xc7, 0x60, 0x15, 0x79, 0x48, 0x22, 0x92, 0xf8, 0xcc, 0x2a,
	0x72, 0xfa, 0x06, 0xdc, 0xac, 0xf9, 0x7d, 0xe0, 0x32, 0xb4, 0x22, 0x92, 0x04, 0xeb, 0xc9, 0xaa,
	0x9d, 0xb5, 0xd1, 0x65, 0x86, 0x6d, 0xba, 0x00, 0xaf, 0x32, 0x33, 0x42, 0x5b, 0x93, 0xd3, 0x8e,
	0xc4, 0xd9, 0xac, 0x05, 0xe8, 0x2b, 0x70, 0x8a, 0xf2, 0xd4, 0xc8, 0x70, 0xa0, 0xc9, 0x71, 0x47,
	0x6e, 0x55, 0x95, 0x99, 0xa6, 0x92, 0x16, 0x8d, 0x54, 0x98, 0xd3, 0x93, 0xfe, 0xae, 0xcb, 0x0c,
	0xdb, 0xf1, 0x12, 0x5c, 0x63, 0xe6, 0xca, 0x3d, 0x85, 0x41, 0x99, 0xfe, 0xe1, 0xda, 0xbb, 0xcf,
	0x74, 0x1c, 0xbf, 0x05, 0x47, 0xcb, 0xdc, 0x04, 0x2f, 0xc1, 0x35, 0x62, 0x37, 0xd1, 0xaf, 0x21,
	0xf8, 0xc6, 0xd3, 0x9c, 0x57, 0x3f, 0xd3, 0x63, 0xc3, 0xe9, 0x0c, 0xdc, 0x7f, 0x2a, 0xa8, 0x43,
	0x12, 0xd9, 0x89, 0xcf, 0x30, 0x8b, 0xef, 0x09, 0xb8, 0x86, 0xa3, 0x1f, 0xc0, 0xdb, 0xeb, 0xa8,
	0x0e, 0xed, 0xc8, 0x4e, 0x82, 0xf5, 0xcb, 0xee, 0x90, 0x86, 0xc0, 0x4f, 0xfd, 0xb9, 0x94, 0xd5,
	0x99, 0xb5, 0xf0, 0xfc, 0x07, 0x0c, 0x2f, 0x1b, 0x74, 0x0a, 0xf6, 0x81, 0x9f, 0xd1, 0x9e, 0x0a,
	0xe9, 0x02, 0x1c, 0x2d, 0x87, 0xef, 0xf6, 0xbc, 0x37, 0x57, 0x3b, 0x64, 0x06, 0xf9, 0x64, 0x7d,
	0x24, 0xf1, 0x1d, 0x01, 0xaf, 0x5d, 0x82, 0x08, 0x82, 0x9c, 0xd7, 0xb2, 0x28, 0x53, 0x59, 0x88,
	0x12, 0xa7, 0x5e, 0x96, 0xd4, 0xe9, 0x33, 0x91, 0x9f, 0xf5, 0xf0, 0x21, 0xd3, 0xb1, 0x7a, 0x2f,
	0x63, 0x0f, 0x17, 0x60, 0xd2, 0x93, 0x64, 0xd8, 0x56, 0xf7, 0xb2, 0xe3, 0x72, 0x2f, 0x72, 0xfd,
	0xfe, 0x3e, 0xc3, 0x2c, 0xde, 0xc2, 0x08, 0xb7, 0xf1, 0x4b, 0x71, 0x94, 0x06, 0xc4, 0xe5, 0x33,
	0x16, 0xda, 0x5d, 0xeb, 0xf9, 0xb3, 0xae, 0xfc, 0xad, 0x77, 0xe0, 0xe1, 0x28, 0xba, 0x81, 0xe0,
	0x2b, 0x97, 0x98, 0xd5, 0x74, 0xd6, 0xb9, 0x7a, 0xa2, 0x35, 0x7f, 0xd1, 0xaf, 0xe3, 0x65, 0xc4,
	0xcf, 0xde, 0x91, 0xcc, 0xd5, 0x3f, 0xce, 0xfb, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x92,
	0x5a, 0x69, 0x49, 0x03, 0x00, 0x00,
}
